name: snippets
description: A package for parsing and manipulating code samples in Flutter repo dartdoc comments.
repository: https://github.com/flutter/assets-for-api-docs/tree/master/packages/snippets
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+snippets%22
version: 0.3.0

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  analyzer: 4.3.1
  args: ^2.0.0
  dart_style: ^2.2.3
  file: ^6.1.0
  interval_tree: ^0.3.0
  meta: ^1.3.0
  path: ^1.8.0
  platform: ^3.0.0
  process: ^4.1.1
  pub_semver: ^2.0.0
  quiver: ^3.0.0
  recase: ^4.0.0

dev_dependencies:
  watcher: ^1.0.0
  test: ^1.21.1

executables:
  snippets:
