name: generator
description: Generator script for building API doc assets.

dependencies:
  animation_metadata:
    path: ../packages/animation_metadata
  archive: ^3.1.2
  process_runner: ">=4.0.0 <5.0.0"

dev_dependencies:
  args: ^2.3.1
  analyzer: ^4.1.0
  test: ^1.16.8
  path: ^1.8.0
  process: ^4.2.1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

