name: generator
description: Generator script for building API doc assets.

dependencies:
  archive: 2.0.3
  process: 3.0.5
  animation_metadata:
    path: ../packages/animation_metadata

dev_dependencies:
  mockito: any
  test: ^1.5.1+1
  
environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"

