name: diagram_generator
description: Main app for building API doc assets.
repository: https://github.com/flutter/assets-for-api-docs/tree/master/packages/diagram_generator
issue_tracker: https://github.com/flutter/flutter/issues
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=1.0.0 <4.0.0"

dependencies:
  archive: ^3.1.2
  args: ^2.3.1
  cupertino_icons: ^1.0.2
  diagram_capture:
    path: ../../packages/diagram_capture
  diagrams:
    path: ../../packages/diagrams
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.1
  platform: ^3.0.0
  process: ^4.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Barriecito
      fonts:
        - asset: fonts/Barriecito-Regular.ttf

    - family: BioRhyme Expanded
      fonts:
        - asset: fonts/BioRhymeExpanded-ExtraBold.ttf

    - family: Cardo
      fonts:
        - asset: fonts/Cardo-Regular.ttf

    - family: Gothic A1
      fonts:
        - asset: fonts/GothicA1-ExtraBold.ttf

    - family: Kufam
      fonts:
        - asset: fonts/Kufam-SemiBold.ttf

    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSansCJKjp-Bold.otf

    - family: Piazzolla
      fonts:
        - asset: fonts/Piazzolla-ExtraBold.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Sorts Mill Goudy
      fonts:
        - asset: fonts/SortsMillGoudy-Regular.ttf

    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Bold.ttf

    - family: Ubuntu Mono
      fonts:
        - asset: fonts/UbuntuMono-Bold.ttf
