name: diagram
description: A package for creating diagrams with Flutter.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  image: ^1.0.30

# The following section is specific to Flutter.
flutter:
