name: snippets_example
version: 1.0.0
description: A code snippet dartdoc extension for Flutter API docs.
homepage: https://github.com/flutter/flutter
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dartdoc:
  nodoc: true

dependencies:
  args: ^2.0.0
  file: ^6.1.0
  snippets:
    path: ..

dev_dependencies:
  test: ^1.16.8

executables:
  snippets: bin/main.dart


