name: simple
description: A simple example of how to use the diagram_capture library.
repository: https://github.com/flutter/assets-for-api-docs/tree/master/packages/diagram_capture/example
issue_tracker: https://github.com/flutter/flutter/issues
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=0.1.4 <4.0.0"

dependencies:
  diagram_capture:
    path: ..
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
