name: simple
description: A simple example of how to use the diagram_capture library.

dependencies:
  diagram_capture:
    path: ..
  flutter:
    sdk: flutter
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
