name: animation_metadata
description: A package that just defines how metadata for an animation is held.

publish_to: none

version: 0.0.1
author: Chromium Authors
homepage: http://www.flutter.dev

dependencies:
  path: ^1.6.4

environment:
  sdk: ">=2.8.0 <3.0.0"

